/* File: TidalLove_individualmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Fri Jun 15 20:05:28 2018
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <string.h>
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *TidalLove_individual_error;
static PyObject *TidalLove_individual_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
typedef char * string;

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
\
#define FAILNULL(p) do {                                            \
    if ((p) == NULL) {                                              \
        PyErr_SetString(PyExc_MemoryError, "NULL pointer found");   \
        goto capi_fail;                                             \
    }                                                               \
} while (0)

#define STRINGMALLOC(str,len)\
    if ((str = (string)malloc(sizeof(char)*(len+1))) == NULL) {\
        PyErr_SetString(PyExc_MemoryError, "out of memory");\
        goto capi_fail;\
    } else {\
        (str)[len] = '\0';\
    }

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define STRINGFREE(str) do {if (!(str == NULL)) free(str);} while (0)

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#define CHECKSCALAR(check,tcheck,name,show,var)\
    if (!(check)) {\
        char errstring[256];\
        sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
        PyErr_SetString(TidalLove_individual_error,errstring);\
        /*goto capi_fail;*/\
    } else 
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) _F2PYWRAP##F
#else
#define F_WRAPPEDFUNC(f,F) _f2pywrap##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) _F2PYWRAP##F##_
#else
#define F_WRAPPEDFUNC(f,F) _f2pywrap##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) F2PYWRAP##F
#else
#define F_WRAPPEDFUNC(f,F) f2pywrap##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) F2PYWRAP##F##_
#else
#define F_WRAPPEDFUNC(f,F) f2pywrap##f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_WRAPPEDFUNC_US(f,F) F_WRAPPEDFUNC(f##_,F##_)
#else
#define F_WRAPPEDFUNC_US(f,F) F_WRAPPEDFUNC(f,F)
#endif

#define STRINGCOPYN(to,from,buf_size)                           \
    do {                                                        \
        int _m = (buf_size);                                    \
        char *_to = (to);                                       \
        char *_from = (from);                                   \
        FAILNULL(_to); FAILNULL(_from);                         \
        (void)strncpy(_to, _from, sizeof(char)*_m);             \
        _to[_m-1] = '\0';                                      \
        /* Padding with spaces instead of nulls */              \
        for (_m -= 2; _m >= 0 && _to[_m] == '\0'; _m--) {      \
            _to[_m] = ' ';                                      \
        }                                                       \
    } while (0)


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyFloat_Check(obj)) {
#ifdef __sgi
        *v = PyFloat_AsDouble(obj);
#else
        *v = PyFloat_AS_DOUBLE(obj);
#endif
        return 1;
    }
    tmp = PyNumber_Float(obj);
    if (tmp) {
#ifdef __sgi
        *v = PyFloat_AsDouble(tmp);
#else
        *v = PyFloat_AS_DOUBLE(tmp);
#endif
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = TidalLove_individual_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}

static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int float_from_pyobj(float* v,PyObject *obj,const char *errmess) {
    double d=0.0;
    if (double_from_pyobj(&d,obj,errmess)) {
        *v = (float)d;
        return 1;
    }
    return 0;
}

static int string_from_pyobj(string *str,int *len,const string inistr,PyObject *obj,const char *errmess) {
    PyArrayObject *arr = NULL;
    PyObject *tmp = NULL;
#ifdef DEBUGCFUNCS
fprintf(stderr,"string_from_pyobj(str='%s',len=%d,inistr='%s',obj=%p)\n",(char*)str,*len,(char *)inistr,obj);
#endif
    if (obj == Py_None) {
        if (*len == -1)
            *len = strlen(inistr); /* Will this cause problems? */
        STRINGMALLOC(*str,*len);
        STRINGCOPYN(*str,inistr,*len+1);
        return 1;
    }
    if (PyArray_Check(obj)) {
        if ((arr = (PyArrayObject *)obj) == NULL)
            goto capi_fail;
        if (!ISCONTIGUOUS(arr)) {
            PyErr_SetString(PyExc_ValueError,"array object is non-contiguous.");
            goto capi_fail;
        }
        if (*len == -1)
            *len = (PyArray_ITEMSIZE(arr))*PyArray_SIZE(arr);
        STRINGMALLOC(*str,*len);
        STRINGCOPYN(*str,PyArray_DATA(arr),*len+1);
        return 1;
    }
    if (PyString_Check(obj)) {
        tmp = obj;
        Py_INCREF(tmp);
    }
#if PY_VERSION_HEX >= 0x03000000
    else if (PyUnicode_Check(obj)) {
        tmp = PyUnicode_AsASCIIString(obj);
    }
    else {
        PyObject *tmp2;
        tmp2 = PyObject_Str(obj);
        if (tmp2) {
            tmp = PyUnicode_AsASCIIString(tmp2);
            Py_DECREF(tmp2);
        }
        else {
            tmp = NULL;
        }
    }
#else
    else {
        tmp = PyObject_Str(obj);
    }
#endif
    if (tmp == NULL) goto capi_fail;
    if (*len == -1)
        *len = PyString_GET_SIZE(tmp);
    STRINGMALLOC(*str,*len);
    STRINGCOPYN(*str,PyString_AS_STRING(tmp),*len+1);
    Py_DECREF(tmp);
    return 1;
capi_fail:
    Py_XDECREF(tmp);
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = TidalLove_individual_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyInt_Check(obj)) {
        *v = (int)PyInt_AS_LONG(obj);
        return 1;
    }
    tmp = PyNumber_Int(obj);
    if (tmp) {
        *v = PyInt_AS_LONG(tmp);
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = TidalLove_individual_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC_US(TidalLove_individual,TIDALLOVE_INDIVIDUAL)(string,float*,float*,float*,float*,float*,size_t);
extern void F_FUNC(CSPLIN,CSPLIN)(int*,double*,double*,double*,double*,double*);
extern void F_WRAPPEDFUNC(cseval,CSEVAL)(double*,int*,double*,int*,double*,double*,double*,double*,double*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/**************************** TidalLove_individual ****************************/
static char doc_f2py_rout_TidalLove_individual_TidalLove_individual[] = "\
mass_out,radius_out,lambda_out = TidalLove_individual(EOS_filename,pc,surface_pressure)\n\nWrapper for ``TidalLove_individual``.\
\n\nParameters\n----------\n"
"EOS_filename : input string(len=-1)\n"
"pc : input float\n"
"surface_pressure : input float\n"
"\nReturns\n-------\n"
"mass_out : float\n"
"radius_out : float\n"
"lambda_out : float";
/* extern void F_FUNC_US(TidalLove_individual,TIDALLOVE_INDIVIDUAL)(string,float*,float*,float*,float*,float*,size_t); */
static PyObject *f2py_rout_TidalLove_individual_TidalLove_individual(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(string,float*,float*,float*,float*,float*,size_t)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  string EOS_filename = NULL;
  int slen(EOS_filename);
  PyObject *EOS_filename_capi = Py_None;
  float pc = 0;
  PyObject *pc_capi = Py_None;
  float surface_pressure = 0;
  PyObject *surface_pressure_capi = Py_None;
  float mass_out = 0;
  float radius_out = 0;
  float lambda_out = 0;
  static char *capi_kwlist[] = {"EOS_filename","pc","surface_pressure",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO:TidalLove_individual.TidalLove_individual",\
    capi_kwlist,&EOS_filename_capi,&pc_capi,&surface_pressure_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable pc */
    f2py_success = float_from_pyobj(&pc,pc_capi,"TidalLove_individual.TidalLove_individual() 2nd argument (pc) can't be converted to float");
  if (f2py_success) {
  /* Processing variable EOS_filename */
  slen(EOS_filename) = -1;
  f2py_success = string_from_pyobj(&EOS_filename,&slen(EOS_filename),"",EOS_filename_capi,"string_from_pyobj failed in converting 1st argument `EOS_filename' of TidalLove_individual.TidalLove_individual to C string");
  if (f2py_success) {
  /* Processing variable mass_out */
  /* Processing variable surface_pressure */
    f2py_success = float_from_pyobj(&surface_pressure,surface_pressure_capi,"TidalLove_individual.TidalLove_individual() 3rd argument (surface_pressure) can't be converted to float");
  if (f2py_success) {
  /* Processing variable lambda_out */
  /* Processing variable radius_out */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(EOS_filename,&pc,&surface_pressure,&mass_out,&radius_out,&lambda_out,slen(EOS_filename));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("fff",mass_out,radius_out,lambda_out);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable radius_out */
  /* End of cleaning variable lambda_out */
  } /*if (f2py_success) of surface_pressure*/
  /* End of cleaning variable surface_pressure */
  /* End of cleaning variable mass_out */
    STRINGFREE(EOS_filename);
  }  /*if (f2py_success) of EOS_filename*/
  /* End of cleaning variable EOS_filename */
  } /*if (f2py_success) of pc*/
  /* End of cleaning variable pc */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/************************ end of TidalLove_individual ************************/

/*********************************** CSPLIN ***********************************/
static char doc_f2py_rout_TidalLove_individual_CSPLIN[] = "\
CSPLIN(X,Y,B,C,D,[N])\n\nWrapper for ``CSPLIN``.\
\n\nParameters\n----------\n"
"X : input rank-1 array('d') with bounds (N)\n"
"Y : input rank-1 array('d') with bounds (N)\n"
"B : input rank-1 array('d') with bounds (N)\n"
"C : input rank-1 array('d') with bounds (N)\n"
"D : input rank-1 array('d') with bounds (N)\n"
"\nOther Parameters\n----------------\n"
"N : input int, optional\n    Default: len(X)";
/* extern void F_FUNC(CSPLIN,CSPLIN)(int*,double*,double*,double*,double*,double*); */
static PyObject *f2py_rout_TidalLove_individual_CSPLIN(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,double*,double*,double*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int N = 0;
  PyObject *N_capi = Py_None;
  double *X = NULL;
  npy_intp X_Dims[1] = {-1};
  const int X_Rank = 1;
  PyArrayObject *capi_X_tmp = NULL;
  int capi_X_intent = 0;
  PyObject *X_capi = Py_None;
  double *Y = NULL;
  npy_intp Y_Dims[1] = {-1};
  const int Y_Rank = 1;
  PyArrayObject *capi_Y_tmp = NULL;
  int capi_Y_intent = 0;
  PyObject *Y_capi = Py_None;
  double *B = NULL;
  npy_intp B_Dims[1] = {-1};
  const int B_Rank = 1;
  PyArrayObject *capi_B_tmp = NULL;
  int capi_B_intent = 0;
  PyObject *B_capi = Py_None;
  double *C = NULL;
  npy_intp C_Dims[1] = {-1};
  const int C_Rank = 1;
  PyArrayObject *capi_C_tmp = NULL;
  int capi_C_intent = 0;
  PyObject *C_capi = Py_None;
  double *D = NULL;
  npy_intp D_Dims[1] = {-1};
  const int D_Rank = 1;
  PyArrayObject *capi_D_tmp = NULL;
  int capi_D_intent = 0;
  PyObject *D_capi = Py_None;
  static char *capi_kwlist[] = {"X","Y","B","C","D","N",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOO|O:TidalLove_individual.CSPLIN",\
    capi_kwlist,&X_capi,&Y_capi,&B_capi,&C_capi,&D_capi,&N_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable X */
  ;
  capi_X_intent |= F2PY_INTENT_IN;
  capi_X_tmp = array_from_pyobj(NPY_DOUBLE,X_Dims,X_Rank,capi_X_intent,X_capi);
  if (capi_X_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(TidalLove_individual_error,"failed in converting 1st argument `X' of TidalLove_individual.CSPLIN to C/Fortran array" );
  } else {
    X = (double *)(PyArray_DATA(capi_X_tmp));

  /* Processing variable N */
  if (N_capi == Py_None) N = len(X); else
    f2py_success = int_from_pyobj(&N,N_capi,"TidalLove_individual.CSPLIN() 1st keyword (N) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(X)>=N,"len(X)>=N","1st keyword N","CSPLIN:N=%d",N) {
  /* Processing variable Y */
  Y_Dims[0]=N;
  capi_Y_intent |= F2PY_INTENT_IN;
  capi_Y_tmp = array_from_pyobj(NPY_DOUBLE,Y_Dims,Y_Rank,capi_Y_intent,Y_capi);
  if (capi_Y_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(TidalLove_individual_error,"failed in converting 2nd argument `Y' of TidalLove_individual.CSPLIN to C/Fortran array" );
  } else {
    Y = (double *)(PyArray_DATA(capi_Y_tmp));

  /* Processing variable C */
  C_Dims[0]=N;
  capi_C_intent |= F2PY_INTENT_IN;
  capi_C_tmp = array_from_pyobj(NPY_DOUBLE,C_Dims,C_Rank,capi_C_intent,C_capi);
  if (capi_C_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(TidalLove_individual_error,"failed in converting 4th argument `C' of TidalLove_individual.CSPLIN to C/Fortran array" );
  } else {
    C = (double *)(PyArray_DATA(capi_C_tmp));

  /* Processing variable B */
  B_Dims[0]=N;
  capi_B_intent |= F2PY_INTENT_IN;
  capi_B_tmp = array_from_pyobj(NPY_DOUBLE,B_Dims,B_Rank,capi_B_intent,B_capi);
  if (capi_B_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(TidalLove_individual_error,"failed in converting 3rd argument `B' of TidalLove_individual.CSPLIN to C/Fortran array" );
  } else {
    B = (double *)(PyArray_DATA(capi_B_tmp));

  /* Processing variable D */
  D_Dims[0]=N;
  capi_D_intent |= F2PY_INTENT_IN;
  capi_D_tmp = array_from_pyobj(NPY_DOUBLE,D_Dims,D_Rank,capi_D_intent,D_capi);
  if (capi_D_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(TidalLove_individual_error,"failed in converting 5th argument `D' of TidalLove_individual.CSPLIN to C/Fortran array" );
  } else {
    D = (double *)(PyArray_DATA(capi_D_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&N,X,Y,B,C,D);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_D_tmp!=D_capi) {
    Py_XDECREF(capi_D_tmp); }
  }  /*if (capi_D_tmp == NULL) ... else of D*/
  /* End of cleaning variable D */
  if((PyObject *)capi_B_tmp!=B_capi) {
    Py_XDECREF(capi_B_tmp); }
  }  /*if (capi_B_tmp == NULL) ... else of B*/
  /* End of cleaning variable B */
  if((PyObject *)capi_C_tmp!=C_capi) {
    Py_XDECREF(capi_C_tmp); }
  }  /*if (capi_C_tmp == NULL) ... else of C*/
  /* End of cleaning variable C */
  if((PyObject *)capi_Y_tmp!=Y_capi) {
    Py_XDECREF(capi_Y_tmp); }
  }  /*if (capi_Y_tmp == NULL) ... else of Y*/
  /* End of cleaning variable Y */
  } /*CHECKSCALAR(len(X)>=N)*/
  } /*if (f2py_success) of N*/
  /* End of cleaning variable N */
  if((PyObject *)capi_X_tmp!=X_capi) {
    Py_XDECREF(capi_X_tmp); }
  }  /*if (capi_X_tmp == NULL) ... else of X*/
  /* End of cleaning variable X */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of CSPLIN *******************************/

/*********************************** CSEVAL ***********************************/
static char doc_f2py_rout_TidalLove_individual_CSEVAL[] = "\
CSEVAL = CSEVAL(U,IDERIV,X,Y,B,C,D,[N])\n\nWrapper for ``CSEVAL``.\
\n\nParameters\n----------\n"
"U : input float\n"
"IDERIV : input int\n"
"X : input rank-1 array('d') with bounds (N)\n"
"Y : input rank-1 array('d') with bounds (N)\n"
"B : input rank-1 array('d') with bounds (N)\n"
"C : input rank-1 array('d') with bounds (N)\n"
"D : input rank-1 array('d') with bounds (N)\n"
"\nOther Parameters\n----------------\n"
"N : input int, optional\n    Default: len(X)\n"
"\nReturns\n-------\n"
"CSEVAL : float";
/* extern void F_WRAPPEDFUNC(cseval,CSEVAL)(double*,int*,double*,int*,double*,double*,double*,double*,double*); */
static PyObject *f2py_rout_TidalLove_individual_CSEVAL(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,int*,double*,int*,double*,double*,double*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double CSEVAL = 0;
  int N = 0;
  PyObject *N_capi = Py_None;
  double U = 0;
  PyObject *U_capi = Py_None;
  int IDERIV = 0;
  PyObject *IDERIV_capi = Py_None;
  double *X = NULL;
  npy_intp X_Dims[1] = {-1};
  const int X_Rank = 1;
  PyArrayObject *capi_X_tmp = NULL;
  int capi_X_intent = 0;
  PyObject *X_capi = Py_None;
  double *Y = NULL;
  npy_intp Y_Dims[1] = {-1};
  const int Y_Rank = 1;
  PyArrayObject *capi_Y_tmp = NULL;
  int capi_Y_intent = 0;
  PyObject *Y_capi = Py_None;
  double *B = NULL;
  npy_intp B_Dims[1] = {-1};
  const int B_Rank = 1;
  PyArrayObject *capi_B_tmp = NULL;
  int capi_B_intent = 0;
  PyObject *B_capi = Py_None;
  double *C = NULL;
  npy_intp C_Dims[1] = {-1};
  const int C_Rank = 1;
  PyArrayObject *capi_C_tmp = NULL;
  int capi_C_intent = 0;
  PyObject *C_capi = Py_None;
  double *D = NULL;
  npy_intp D_Dims[1] = {-1};
  const int D_Rank = 1;
  PyArrayObject *capi_D_tmp = NULL;
  int capi_D_intent = 0;
  PyObject *D_capi = Py_None;
  static char *capi_kwlist[] = {"U","IDERIV","X","Y","B","C","D","N",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOO|O:TidalLove_individual.CSEVAL",\
    capi_kwlist,&U_capi,&IDERIV_capi,&X_capi,&Y_capi,&B_capi,&C_capi,&D_capi,&N_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable IDERIV */
    f2py_success = int_from_pyobj(&IDERIV,IDERIV_capi,"TidalLove_individual.CSEVAL() 2nd argument (IDERIV) can't be converted to int");
  if (f2py_success) {
  /* Processing variable CSEVAL */
  /* Processing variable U */
    f2py_success = double_from_pyobj(&U,U_capi,"TidalLove_individual.CSEVAL() 1st argument (U) can't be converted to double");
  if (f2py_success) {
  /* Processing variable X */
  ;
  capi_X_intent |= F2PY_INTENT_IN;
  capi_X_tmp = array_from_pyobj(NPY_DOUBLE,X_Dims,X_Rank,capi_X_intent,X_capi);
  if (capi_X_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(TidalLove_individual_error,"failed in converting 3rd argument `X' of TidalLove_individual.CSEVAL to C/Fortran array" );
  } else {
    X = (double *)(PyArray_DATA(capi_X_tmp));

  /* Processing variable N */
  if (N_capi == Py_None) N = len(X); else
    f2py_success = int_from_pyobj(&N,N_capi,"TidalLove_individual.CSEVAL() 1st keyword (N) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(X)>=N,"len(X)>=N","1st keyword N","CSEVAL:N=%d",N) {
  /* Processing variable Y */
  Y_Dims[0]=N;
  capi_Y_intent |= F2PY_INTENT_IN;
  capi_Y_tmp = array_from_pyobj(NPY_DOUBLE,Y_Dims,Y_Rank,capi_Y_intent,Y_capi);
  if (capi_Y_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(TidalLove_individual_error,"failed in converting 4th argument `Y' of TidalLove_individual.CSEVAL to C/Fortran array" );
  } else {
    Y = (double *)(PyArray_DATA(capi_Y_tmp));

  /* Processing variable D */
  D_Dims[0]=N;
  capi_D_intent |= F2PY_INTENT_IN;
  capi_D_tmp = array_from_pyobj(NPY_DOUBLE,D_Dims,D_Rank,capi_D_intent,D_capi);
  if (capi_D_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(TidalLove_individual_error,"failed in converting 7th argument `D' of TidalLove_individual.CSEVAL to C/Fortran array" );
  } else {
    D = (double *)(PyArray_DATA(capi_D_tmp));

  /* Processing variable C */
  C_Dims[0]=N;
  capi_C_intent |= F2PY_INTENT_IN;
  capi_C_tmp = array_from_pyobj(NPY_DOUBLE,C_Dims,C_Rank,capi_C_intent,C_capi);
  if (capi_C_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(TidalLove_individual_error,"failed in converting 6th argument `C' of TidalLove_individual.CSEVAL to C/Fortran array" );
  } else {
    C = (double *)(PyArray_DATA(capi_C_tmp));

  /* Processing variable B */
  B_Dims[0]=N;
  capi_B_intent |= F2PY_INTENT_IN;
  capi_B_tmp = array_from_pyobj(NPY_DOUBLE,B_Dims,B_Rank,capi_B_intent,B_capi);
  if (capi_B_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(TidalLove_individual_error,"failed in converting 5th argument `B' of TidalLove_individual.CSEVAL to C/Fortran array" );
  } else {
    B = (double *)(PyArray_DATA(capi_B_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&CSEVAL,&N,&U,&IDERIV,X,Y,B,C,D);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("d",CSEVAL);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_B_tmp!=B_capi) {
    Py_XDECREF(capi_B_tmp); }
  }  /*if (capi_B_tmp == NULL) ... else of B*/
  /* End of cleaning variable B */
  if((PyObject *)capi_C_tmp!=C_capi) {
    Py_XDECREF(capi_C_tmp); }
  }  /*if (capi_C_tmp == NULL) ... else of C*/
  /* End of cleaning variable C */
  if((PyObject *)capi_D_tmp!=D_capi) {
    Py_XDECREF(capi_D_tmp); }
  }  /*if (capi_D_tmp == NULL) ... else of D*/
  /* End of cleaning variable D */
  if((PyObject *)capi_Y_tmp!=Y_capi) {
    Py_XDECREF(capi_Y_tmp); }
  }  /*if (capi_Y_tmp == NULL) ... else of Y*/
  /* End of cleaning variable Y */
  } /*CHECKSCALAR(len(X)>=N)*/
  } /*if (f2py_success) of N*/
  /* End of cleaning variable N */
  if((PyObject *)capi_X_tmp!=X_capi) {
    Py_XDECREF(capi_X_tmp); }
  }  /*if (capi_X_tmp == NULL) ... else of X*/
  /* End of cleaning variable X */
  } /*if (f2py_success) of U*/
  /* End of cleaning variable U */
  /* End of cleaning variable CSEVAL */
  } /*if (f2py_success) of IDERIV*/
  /* End of cleaning variable IDERIV */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of CSEVAL *******************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"TidalLove_individual",-1,{{-1}},0,(char *)F_FUNC_US(TidalLove_individual,TIDALLOVE_INDIVIDUAL),(f2py_init_func)f2py_rout_TidalLove_individual_TidalLove_individual,doc_f2py_rout_TidalLove_individual_TidalLove_individual},
  {"CSPLIN",-1,{{-1}},0,(char *)F_FUNC(CSPLIN,CSPLIN),(f2py_init_func)f2py_rout_TidalLove_individual_CSPLIN,doc_f2py_rout_TidalLove_individual_CSPLIN},
  {"CSEVAL",-1,{{-1}},0,(char *)F_WRAPPEDFUNC(cseval,CSEVAL),(f2py_init_func)f2py_rout_TidalLove_individual_CSEVAL,doc_f2py_rout_TidalLove_individual_CSEVAL},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "TidalLove_individual",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit_TidalLove_individual(void) {
#else
#define RETVAL
PyMODINIT_FUNC initTidalLove_individual(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = TidalLove_individual_module = PyModule_Create(&moduledef);
#else
  m = TidalLove_individual_module = Py_InitModule("TidalLove_individual", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module TidalLove_individual (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'TidalLove_individual' is auto-generated with f2py (version:2).\nFunctions:\n"
"  mass_out,radius_out,lambda_out = TidalLove_individual(EOS_filename,pc,surface_pressure)\n"
"  CSPLIN(X,Y,B,C,D,N=len(X))\n"
"  CSEVAL = CSEVAL(U,IDERIV,X,Y,B,C,D,N=len(X))\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  TidalLove_individual_error = PyErr_NewException ("TidalLove_individual.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));



    {
      extern double F_FUNC(cseval,CSEVAL)(void);
      PyObject* o = PyDict_GetItemString(d,"CSEVAL");
      PyObject_SetAttrString(o,"_cpointer", F2PyCapsule_FromVoidPtr((void*)F_FUNC(cseval,CSEVAL),NULL));
#if PY_VERSION_HEX >= 0x03000000
      PyObject_SetAttrString(o,"__name__", PyUnicode_FromString("CSEVAL"));
#else
      PyObject_SetAttrString(o,"__name__", PyString_FromString("CSEVAL"));
#endif
    }
    
/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"TidalLove_individual");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
